### ISSUE TITLE
Doesn't detect circular references correctly

### ISSUE THREAD

**Issue by MikeRalphson** [e-conomic/safe-json-stringify#5]
What it detects is object **identity** over objects it has seen before.

Consider the following example

```js
const sjs = require('safe-json-stringify');

const a = { test: 1 };
const b = { c: a, d: a};

console.log(sjs(b));
console.log(JSON.stringify(b));
```

The output is

```
{"c":{"test":1},"d":"[Circular]"}
{"c":{"test":1},"d":{"test":1}}
```

Whereas I would expect

```
{"c":{"test":1},"d":{"test":1}}
{"c":{"test":1},"d":{"test":1}}
```

It correctly identifies real circular references.

**Comment by MikeRalphson** [comment]
PR in progress.

**Comment by ath88** [comment]
@MikeRalphson Any update?

**Comment by MikeRalphson** [comment]
My fix is here: https://github.com/MikeRalphson/safe-json-stringify/commit/754b8f5084ac4126dfc5f5c487d67336b461b486

It needs whitespace cleanup and I'm not sure if its the cleanest way of doing things (placement of the extra `pop`s).

@gausby @jonatanpedersen any comments?

**Comment by jonatanpedersen** [comment]
@MikeRalphson feel free to create a pull request :)
