### ISSUE TITLE
Unable to stringify exceptions

### ISSUE THREAD

**Issue by binarykitchen** [e-conomic/safe-json-stringify#9]
Found out while debugging that your library can't stringify exceptions.

For example `DOMException: The play() request was interrupted by a call to pause()` gets returned as `{}`.

**Comment by ronkorving** [comment]
That's a DOMException, which probably also serializes to `{}` when simply using JSON.stringify, I assume? In which case, I would imagine it's kind of out-of-scope for this library. Error objects don't get any special treatment in this library, they're treated like any other object.

**Comment by binarykitchen** [comment]
alright then
